# Generated by Django 4.2.5 on 2023-09-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('cpf', models.CharField(max_length=11)),
                ('numero_da_conta', models.IntegerField()),
                ('agencia', models.IntegerField()),
                ('senha', models.CharField(max_length=8)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('senha_email', models.CharField(max_length=8)),
            ],
        ),
    ]
